### ISSUE TITLE
Does this still work with latest phoenix 1.5?

### ISSUE THREAD

**Issue by pierre-pretorius** [webstronauts/ex_unpoly#2]
I just started a new project with mix phoenix.new.  Followed the installation instructions of this library and got this error:
```
** (exit) an exception was raised:
    ** (KeyError) key :phoenix_router not found in: %{phoenix_endpoint: NewAppWeb.Endpoint, phoenix_request_logger: {"request_logger", "request_logger"}}
        (phoenix 1.5.4) lib/phoenix/controller.ex:254: Phoenix.Controller.router_module/1
        (phoenix 1.5.4) lib/phoenix/controller.ex:1514: Phoenix.Controller.current_url/1
        (ex_unpoly 1.2.1) lib/unpoly.ex:152: Unpoly.echo_request_headers/1
        (ex_unpoly 1.2.1) lib/unpoly.ex:130: Unpoly.call/2
        (new_app 0.1.0) lib/new_app_web/endpoint.ex:1: NewAppWeb.Endpoint.plug_builder_call/2
```

**Comment by robinvdvleuten** [comment]
It should work, as it just calls the `Phoenix.Controller.current_url()` helper. It just reads the currnet location and adds a couple of response headers. 
Did you call the plug within a router pipeline or within the endpoint?
